### ISSUE TITLE
Stackage nightly: Build failure

### ISSUE THREAD

**Issue by decentral1se** [tvh/haxl-amazonka#1]
```
Building haxl-amazonka-0.1.0.0...
Preprocessing library haxl-amazonka-0.1.0.0...
[1 of 1] Compiling Network.AWS.DataSource ( lib/Network/AWS/DataSource.hs, dist/build/Network/AWS/DataSource.o )

lib/Network/AWS/DataSource.hs:71:10: error:
    Not in scope: type constructor or class ‘Show1’
    Perhaps you meant one of these:
      ‘Show’ (imported from Prelude), ‘ShowS’ (imported from Prelude),
      ‘ShowP’ (imported from Haxl.Core)
```

**Comment by lwm** [comment]
My apologies for disabling the package. I'm the new guy ;)

So, the failure is due to one the deps , namely ClustalParser, making a breaking change in 1.2.0.

I've re-enabled RNAlien and placed an upper bounds on ClustalParser.

Sorry for any confusion :+1:

**Comment by decentral1se** [comment]
My apologies for disabling the package! The newest release of haxl (0.5.0.0) broke this package. I've placed an upper bound on haxl until you have a chance to resolve this. Sorry for any confusion :+1:
